version: "3.2"
services:
  php:
    build: './php/'
    networks:
      - enpns1cr0h5imlt6npke
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
    networks:
      - frontend
      - enpns1cr0h5imlt6npke
    ports:
      - "80:80"
    volumes:
      - ./public_html/:/var/www/html/
networks:
  frontend:
  enpns1cr0h5imlt6npke: